Create 2022-12-08-nginxplus-monitoring.md
netdata/blog pull request #152
Opened 2022-12-08 13:45 UTC by sashwathn

Trial of the Streamlit autoblogger app from Shyam

2022-12-08 13:57 UTC, andrewm4894 commented
@sashwathn 

```
Error: Blog author with key "Netdata" not found in the authors map file.
```

2022-12-08 13:57 UTC, andrewm4894 commented on blog/2022-12-08-nginxplus-monitoring.md
> +authors: Netdata
```suggestion
authors: team
```

2022-12-22 18:12 UTC, hugovalente-pm requested changes
Just a minor check on naming of NGING and NGINXPLus, besides that all looks 👌

2022-12-22 18:12 UTC, hugovalente-pm commented on blog/2022-12-08-nginxplus-monitoring.md
> +Nginx Plus is an open source web server and load balancer. It is an enterprise-grade version of the popular open source Nginx web server, with additional features for scalability, performance, and mo
```suggestion
NGINXPLus is an open source web server and load balancer. It is an enterprise-grade version of the popular open source NGINX web server, with additional features for scalability, performance, and monitoring. NGINXPLus includes features such as load balancing, content caching, and HTTP/2 support, and is suitable for applications of any size. NGINXPLus is highly customizable and can be used to deploy web applications in a variety of environments.
```

2022-12-22 18:12 UTC, hugovalente-pm commented on blog/2022-12-08-nginxplus-monitoring.md
> +Nginx Plus is an open source web server and load balancer. It is an enterprise-grade version of the popular open source Nginx web server, with additional features for scalability, performance, and mo
minor but just to keep the naming consistent

2022-12-22 19:50 UTC, sashwathn commented
Thanks @hugovalente-pm!

2022-12-22 21:23 UTC, andrewm4894 approved these changes

2022-12-22 21:26 UTC, merged