Blog on interrupts, softirqs and softnets in Linux
netdata/blog pull request #256
Opened 2023-05-02 17:04 UTC by sashwathn

Please review and Approve

2023-05-02 17:07 UTC, andrewm4894 approved these changes

2023-05-02 17:07 UTC, andrewm4894 requested changes
Should there be two posts here?

2023-05-02 18:01 UTC, cakrit requested changes

2023-05-02 18:01 UTC, cakrit commented on blog/2023-05-02-understanding-interrupts-softirqs-and-softnet-in-linux/index.md
> +
```suggestion
![image](https://user-images.githubusercontent.com/43294513/235747305-9f5c8d3a-4e76-43b1-882c-3b1307f1dd41.png)
```

2023-05-02 18:06 UTC, sashwathn commented
@andrewm4894 / @cakrit : Not sure how the context-switching blog came up here. I created a new branch after pushing the other one - weird.

2023-05-02 18:29 UTC, cakrit approved these changes

2023-05-03 07:19 UTC, sashwathn commented
Closing the PR and recreating another one..

2023-05-03 08:44 UTC, sashwathn commented
@andrewm4894 : I fixed the files being committed.

2023-05-03 08:45 UTC, merged