Server uptime monitoring blog
netdata/blog pull request #264
Opened 2023-05-03 13:08 UTC by sashwathn

Please review and approve.

2023-05-03 13:30 UTC, cakrit commented on blog/2023-05-02-server-uptime-monitoring-why-do-we-need-it/index.md
> +    Uptime monitoring can show whether a server is consistently available or experiences frequent downtimes. High uptime indicates the server is reliable and available for users, while low uptime may
```suggestion
  Uptime monitoring can show whether a server is consistently available or experiences frequent downtimes. High uptime indicates the server is reliable and available for users, while low uptime may signal potential issues that need to be addressed.
```

2023-05-03 13:34 UTC, cakrit requested changes
Two more comments:
- The lists don't appear properly in the HTML. You've done proper markdown, but the text on the blog will appear next to the bold items. @andrewm4894 can check if it's something particular to Docusaurus, or we can just go back to using ":" after the bold.
- Please at the bottom add a small section about Netdata. I have a chart screenshot here you can add

![image](https://user-images.githubusercontent.com/43294513/235931152-9797fd58-cc4a-4195-bb37-2a7668fe0f17.png)

2023-05-03 13:34 UTC, cakrit commented on blog/2023-05-02-server-uptime-monitoring-why-do-we-need-it/index.md
> +## Why Server uptime monitoring is important?
```suggestion
## Why is Server Uptime Monitoring Important?
```

2023-05-04 09:38 UTC, sashwathn commented
@cakrit : All changes made. Approve when you get a chance.

2023-05-04 13:41 UTC, cakrit approved these changes

2023-05-04 15:12 UTC, merged